-- MySQL Script generated by MySQL Workbench
-- Thu Nov 17 23:44:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ejercicio5_AppWeb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Ejercicio5_AppWeb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ejercicio5_AppWeb` DEFAULT CHARACTER SET utf8 ;
USE `Ejercicio5_AppWeb` ;

-- -----------------------------------------------------
-- Table `Ejercicio5_AppWeb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio5_AppWeb`.`Usuario` (
  `Codigo` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Clave` VARCHAR(120) NOT NULL,
  `Correo` VARCHAR(45) NULL,
  `Rol` VARCHAR(20) NOT NULL,
  `EstaActivo` TINYINT NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
